# path to the geckodriver executable
search_config:
  # path to the geckodriver executable
  service: "/usr/local/bin/geckodriver"
  search_url: "https://www.uni-osnabrueck.de/universitaet/organisation/zentrale-verwaltung/google-suche/?q="

model:
  model_name: "gpt-4o-mini"
  context_window: 128000

language: "Deutsch"  # Literal["Deutch", "English"]. 