---
- hosts: all
  gather_facts: no
  tasks:

  - name: pull branch
    git:
      repo={{ repo_url }}
      dest={{ home_dir }}
      version={{ branch }}
      accept_hostkey=yes



  - name: Create a virtualenv directory
    file: path={{ venv_dir }} state=directory

  - name: Install dependencies
    pip: requirements={{ repo_dir }}/requirements.txt
      virtualenv={{ venv_dir }}
      virtualenv_python=python3.10

